-- =======================================================
-- Requête #
-- Objectif : ...
-- ...
-- ...
-- Évaluation : ...
-- ...
-- ...
-- Réalisé par : ...
-- Aidé par : ...
-- =======================================================

-- =======================================================

-- ROMAIN

-- NOÉ

-- MATHIS

--JULIETTE
-- =======================================================
-- Requête #
-- Objectif : Donner le nombre d’inspections où chaque employé était conducteur.
-- ...
-- ...
-- Évaluation : 
-- ...
-- ...
-- Réalisé par : Juliette Vincent
-- Aidé par :
-- =======================================================
SELECT COUNT(*)
FROM inspection
WHERE 
GROUP BY 
-- =======================================================